# Generated by Django 5.2.4 on 2026-01-19 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.CharField(max_length=20)),
                ('invoice_no', models.CharField(max_length=20, unique=True)),
                ('bank_name', models.CharField(choices=[('Nabil', 'Nabil Bank'), ('NIC', 'NIC Asia Bank'), ('SBI', 'Nepal SBI Bank'), ('Global', 'Global IME Bank'), ('Prabhu', 'Prabhu Bank'), ('Machha', 'Machhapuchhre Bank'), ('Sanima', 'Sanima Bank'), ('Mega', 'Mega Bank'), ('Kumari', 'Kumari Bank'), ('N/A', 'N/A')], max_length=20)),
                ('bank_ref_no', models.CharField(blank=True, max_length=20, null=True)),
                ('insurance_company', models.CharField(blank=True, choices=[('IME', 'IME Life Insurance Company Limited'), ('Neco', 'Neco Insurance Ltd.'), ('Sanima', 'Sanima GIC Insurance Ltd.'), ('Salico', 'Sagarmatha Lumbini Insurance Company Ltd.'), ('Sidd', 'Siddhartha Premier Insurance Ltd.'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('$', 'USD'), ('₹', 'INR'), ('रु ', 'NPR')], default='USD', max_length=5)),
                ('price_terms', models.CharField(choices=[('DAP', 'DAP'), ('LC', 'LC'), ('TT', 'TT'), ('N/A', 'N/A')], max_length=10)),
                ('payment_terms', models.CharField(choices=[('CFR', 'CFR'), ('CIF', 'CIF'), ('FOB', 'FOB'), ('EXW', 'EXW'), ('N/A', 'N/A')], max_length=10)),
                ('dispatch_date', models.DateField()),
                ('doc_received_date', models.DateField(blank=True, null=True)),
                ('eta_date', models.DateField(blank=True, null=True)),
                ('settlement_date', models.DateField(blank=True, null=True)),
                ('customs_entry_date', models.DateField(blank=True, null=True)),
                ('doc_to_bank', models.DateField(blank=True, null=True)),
                ('pp_no', models.CharField(blank=True, max_length=20, null=True)),
                ('vanshar', models.CharField(blank=True, choices=[('Mechi', 'Mechi'), ('Birgunj', 'Birgunj'), ('Biratnagar', 'Biratnagar'), ('Tatopani', 'Tatopani'), ('TIA', 'Tribhuvan International Airport'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
                'ordering': ['-dispatch_date'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentYatayat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatayat', models.CharField(blank=True, choices=[('Mechi', 'Mechi'), ('Koshi', 'Koshi'), ('Sagarmatha', 'Sagarmatha'), ('Janakpur', 'Janakpur'), ('Bagmati', 'Bagmati'), ('Narayani', 'Narayani'), ('Gandaki', 'Gandaki'), ('Dhaulagiri', 'Dhaulagiri'), ('Lumbini', 'Lumbini'), ('Rapti', 'Rapti'), ('Bheri', 'Bheri'), ('Karnali', 'Karnali'), ('Seti', 'Seti'), ('Mahakali', 'Mahakali'), ('N/A', 'N/A')], max_length=50, null=True)),
                ('chitti_file', models.FileField(blank=True, null=True, upload_to='shipment_chittis/%Y/%m/')),
                ('date_issued', models.DateField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yatayats', to='shipments.shipment')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(editable=False, max_length=15, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical Issue'), ('billing', 'Billing Question'), ('feature', 'Feature Request'), ('general', 'General Inquiry')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], max_length=10)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
