# Generated by Django 5.2.4 on 2026-01-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='margin_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='margin_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
